### ISSUE TITLE
502: API Services rejected request with error. Reason: undefined

### ISSUE THREAD

**Issue by ShouxTech** [nikita-petko/RbxDataStoreService#152]
Attempting to initialize using InitializeAsync throws an obscure error (502: API Services rejected request with error. Reason: undefined)

**To Reproduce**
```js
import { InitializeAsync } from '@mfd/rbxdatastoreservice';

async function init() {
    await InitializeAsync('COOKIE', 123456789);
}

init()
    .then(() => {
        console.log('Successfully initialized');
    })
    .catch((err) => {
        console.error(err); // 502: API Services rejected request with error. Reason: undefined
    });
```

**Expected behavior**
The package should initialize and proceed with no error.

**Screenshots**
https://i.gyazo.com/7169436e88a1ab5548bfc3884b7c68d1.png

This error started happening today.
I suspect that Roblox changed something on their end and it's now rejecting this package's attempt to access the datastore.

**Comment by khizzer123** [comment]
I am also getting this error

**Comment by 1nferious** [comment]
Same here I'm experiencing the same issue!

**Comment by not-masterzz** [comment]
I'm also getting this issue please help!

**Comment by ScreamBirb** [comment]
I'm not getting this issue, don't fix!

**Comment by nikita-petko** [comment]
Oh shoot, I'll look into this now. Please stay tuned!

**Comment by nikita-petko** [comment]
I have found the issue, they decided to remove an endpoint that the package relied on for authentication (an endpoint for checking place ownership).

Shipping out a fix now!

**Comment by nikita-petko** [comment]
@ShouxTech @khizzer123 @1nferious @ScreamBirb @not-masterzz can you please try version 2.3.11?

**Comment by ShouxTech** [comment]
Version 2.3.11 works. Thank you.
